apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-springboot"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/lab-springboot-files:$(workshop_version)"
  workshop:
    image: jdk17-environment:*
    files:
      - image:
          url: "$(image_repository)/lab-springboot-files:$(workshop_version)"
        includePaths:
          - /workshop/**
          - /exercises/**
          - /README.md
      - path: .local/share/code-server/extensions
        image:
          # REQUIRES Educates 2.6.11. url: ghcr.io/vmware-tanzu-learning/vscode-java-extensions-$(platform_arch)-files:2.1.0
          url: ghcr.io/vmware-tanzu-learning/vscode-java-extensions-arm64-files:2.1.0
  session:
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      docker:
        enabled: true
        compose:
          services:
            initializr:
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.1
              ports:
                - target: 8080
                  published: 8080
                  protocol: tcp
                  mode: host
    dashboards:
      - name: Spring Initializr
        url: "$(ingress_protocol)://initializr-$(session_hostname)$(ingress_port_suffix)"
    ingresses:
      - name: initializr
        protocol: http
        host: initializr
        port: 8080
    patches:
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
          - initializr
