apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: "lab-springboot"
spec:
  title: "Workshop"
  description: "Workshop description."
  publish:
    image: "$(image_repository)/lab-springboot-files:$(workshop_version)"
  workshop:
    image: jdk17-environment:*
    files:
      - image:
          url: "$(image_repository)/lab-springboot-files:$(workshop_version)"
        includePaths:
          - /workshop/**
          - /exercises/**
          - /README.md
      - path: .local/share/code-server/extensions
        image:
          url: ghcr.io/vmware-tanzu-learning/vscode-java-extensions-arm64-files:2.1.0
  session:
    namespaces:
      budget: medium
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      docker:
        enabled: true
        compose:
          services:
            initializr-workshop:
              image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.0
              ports:
                # - "127.0.0.1:8080:8080"
                - target: 8080
                  published: 8080
                  protocol: tcp
                  mode: host
    dashboards:
      - name: Spring Initializr
        url: "$(ingress_protocol)://initializr-$(session_hostname)$(ingress_port_suffix)"
    ingresses:
      - name: initializr
        protocol: http
        # host: initializr.$(workshop_namespace).svc.cluster.local
        host: initializr-workshop
        changeOrigin: true
        port: 8080
  environment:
    objects:
      - apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: initializr
          labels:
            app: initializr
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: initializr
          template:
            metadata:
              labels:
                app: initializr
            spec:
              containers:
                - name: dashboard
                  image: ghcr.io/vmware-tanzu-labs/educates-spring-initializr:2.0
                  imagePullPolicy: IfNotPresent
                  ports:
                    - name: 8080-tcp
                      containerPort: 8080
                      protocol: TCP
      - apiVersion: v1
        kind: Service
        metadata:
          name: initializr
          labels:
            app: initializr
        spec:
          type: ClusterIP
          selector:
            app: initializr
          ports:
            - name: 8080-tcp
              port: 8080
              targetPort: 8080
              protocol: TCP
