name: Publish Workshop

on:
  push:
    tags:
      - "[0-9]+.[0-9]+"
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-workshop:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: vmware-tanzu-labs/educates-github-actions/publish-workshop@v6
        with:
          token: ${{secrets.GITHUB_TOKEN}}
        env:
          REPOSITORY_TAG: ${{github.ref_name}}
